# Generated by Django 4.2.3 on 2023-07-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_created_at_project_createt_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='createt_at',
            new_name='created_at',
        ),
    ]
